version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend_net
      - backend_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://zakaria:admin@mongodb:27017/flaskdb?authSource=admin
    volumes:
      - ./backend:/app
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: zakaria
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: flaskdb
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  appdata:
    driver: local
