version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend_net
    tty: true

  backend:
    build: ./backend
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://zakaria:admin@mongodb:27017/flaskdb?authSource=admin
    volumes:
      - ./backend:/app
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: zakaria
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: flaskdb
    networks:
      - backend_net
    volumes:
      - mongo_data:/data/db

networks:
  frontend_net:
  backend_net:

volumes:
  mongo_data:
